baseURL = "https://example.com/"

[module]
[module.hugoVersion]
min = "0.77.0"

title = "MC Chung"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "MC Chung"
  info = "Dept. of Economics, NTU"
  description = "MC's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/me.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/images/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Youtube"
  icon = "fa-brands fa-youtube fa-2x"
  weight = 1
  url = "https://www.youtube.com/channel/UCOllz_clJBkdk5y4Ef8-_Lw"
[[params.social]]
  name = "Medium"
  icon = "fa-brands fa-medium fa-2x"
  weight = 2
  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 3
  url = "https://github.com/workchung1995"


[languages.en]
languageName = "En"
title = "MC Chung"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[menu.main]]
  name = "Post"
  weight = 2
  url  = "posts/"

[[menu.main]]
  name = "Tools"
  weight = 3
  url  = "tools/"

[[menu.main]]
  name = "Resource"
  weight = 4
  url  = "resource/"

# ---------------------------------------------------- #
#                   Chinese                            #
# ---------------------------------------------------- #
[languages.tw]
languageName = "中文"
title = "MC Chung"

[languages.tw.params]
author = "MC Chung"
info = "國立台灣大學 經濟系"
description = "Sítio pessoal de João Ninguém"
keywords = "blog,desenvolvedor,pessoal"


# Menu links
[[languages.tw.menu.main]]
  name = "關於我"
  weight = 1
  url = "about/"

[[languages.tw.menu.main]]
  name = "貼文"
  weight = 2
  url  = "posts/"

[[languages.tw.menu.main]]
  name = "工具"
  weight = 3
  url  = "tools/"

[[languages.tw.menu.main]]
  name = "資源"
  weight = 4
  url = "resource/"